baseURL = "/"
languageCode = "en-gb"
title = "avp group"

enableRobotsTXT = true
disableAliases = true

[imaging]
resampleFilter = "Lanczos"
anchor = "center"

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true


[menu]

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        weight = 20
        url = "/projects/"

    [[menu.main]]
        name = "Solutions"
        weight = 30
        url = "/solutions/"

    # [[menu.main]]
    #     name = "Support"
    #     weight = 40
    #     url = "/support/"

    # [[menu.main]]
    #     name = "Professionals"
    #     weight = 50
    #     url = "/professionals/"

    # [[menu.main]]
    #     name = "Knowledge Hub"
    #     weight = 60
    #     url = "/knowledge-hub/"

    [[menu.main]]
        name = "About"
        weight = 70
        url = "/team/"

    [[menu.main]]
        name = "Contact"
        weight = 80
        url = "/contact/"


    # [[menu.footer]]
    #     name = "Partners"
    #     weight = 10
    #     url = "/partners/"

    [[menu.footer]]
        name = "Privacy Policy"
        weight = 20
        url = "/privacy-policy/"

    # [[menu.footer]]
    #     name = "Terms of Use"
    #     weight = 30
    #     url = "/terms-of-use/"

    [[menu.footer]]
        name = "Cookies"
        weight = 40
        url = "/cookies/"
